services:
  eureka:
    build: ./services
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka:8761"]
      interval: 30s
      timeout: 10s
      retries: 5
  gateway:
    build: ./services
    networks:
      - my-network

    links:
      - eureka
    depends_on:
      eureka:
        condition: service_healthy

networks:
  my-network:
    name: my-network
    
    

    